version: 0.1
log:
  level: info
  formatter: text
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ["*"]
    Access-Control-Allow-Methods: ["GET", "HEAD", "POST", "PUT", "DELETE"]
    Access-Control-Allow-Headers: ["Authorization"]
