version: '3'

services:
  registry:
    image: registry:2
    restart: always
    container_name: registry-server
    ports:
      - "5000:5000"
    volumes:
      - ./data:/var/lib/registry
      - ./certs:/certs
      - ./config.yml:/etc/docker/registry/config.yml
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/domain.key

  registry-ui:
    image: joxit/docker-registry-ui
    restart: always
    container_name: registry-ui-server
    ports:
      - "8090:80"
    environment:
      - REGISTRY_URL=https://IP_ADDRESS:5000/
