version: '3.7'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    # image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server-2019
    environment:
      SA_PASSWORD: "MyStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./backup:/var/opt/mssql/backup
    # test: docker exec -it sql-server-2019 /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P MyStrong!Passw0rd
